### ISSUE TITLE
Housenumber points optimization

### ISSUE THREAD

**Issue by edpop** [mapbox/postgis-vt-util#18]
Hello.
There is a way to calc housenumber points from buildings x5 faster.
Duscussion: https://github.com/openmaptiles/openmaptiles/issues/209
Would you like to have a fast *building_to_point* function?

**Comment by lukasmartinelli** [comment]
Yes! But it would be good to have a more generic name, it's more like simple_shape_to_point function (find a good name).

Ask anything you need to help me implement this!

**Comment by edpop** [comment]
Seems like this repo is abandoned by it's owner.
