### ISSUE TITLE
Expect labelgrid() return null instead of string 'null' 

### ISSUE THREAD

**Issue by helmi03** [mapbox/postgis-vt-util#4]
https://github.com/mapbox/postgis-vt-util/blob/master/lib.sql#L26

ERROR:  parse error - invalid geometry
HINT:  "nu" <-- parse error at position 2 within geometry

I know the solution for my problem,
but any good reason return string 'null' ?

**Comment by ajashton** [comment]
The output of this function is not intended to be parsed as an actual geometry, it's just meant for sorting with one unique string per grid cell.
